FROM node:20-alpine
WORKDIR /app

COPY package*.json ./

EXPOSE 4200

CMD ["sh", "-c", "if [ ! -d node_modules/@angular ]; then npm ci; fi && npm run start:docker -- --host 0.0.0.0 --port 4200 --poll 2000"]
