FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /src

COPY ["WebApp/WebApp.csproj", "WebApp/"]
COPY ["Application/Application.csproj", "Application/"]
COPY ["Domain/Domain.csproj", "Domain/"]
COPY ["Infrastructure/Infrastructure.csproj", "Infrastructure/"]
RUN dotnet restore "WebApp/WebApp.csproj" /p:NuGetAudit=false

EXPOSE 8080

CMD ["sh", "-c", "dotnet restore WebApp/WebApp.csproj /p:NuGetAudit=false && dotnet watch --project WebApp/WebApp.csproj run --no-launch-profile --urls http://+:8080"]
